name = "rald-realtime"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = []

[vars]
ENVIRONMENT = "production"
RALD_AUTH_URL = "https://auth.rald.cloud"

[[routes]]
pattern = "realtime.rald.cloud/*"
zone_name = "rald.cloud"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "5115e9d11424487eaaff71638addff34"

[[kv_namespaces]]
binding = "HEALTH_KV"
id = "36a4c73ff82a4aabae5fa4b604622047"

[[kv_namespaces]]
binding = "PROVIDER_STATE_KV"
id = "91d1b5895a99481588118695fba6bd52"

[build]
command = ""

[observability]
enabled = true
head_sampling_rate = 1
